### ISSUE TITLE
`npm install chimera` on ubuntu installs broken chimera

### ISSUE THREAD

**Issue by Trindaz** [deanmao/node-chimera#17]
Fresh instance of Ubuntu 12 on AWS, upgrade to node.js 0.8.17, then create a new node.js project and do the old 'npm install chimera'.

Then run 'node index2.js' (using sample code from READM.md) I get this:

Error loading chimera in lib

/home/ubuntu/talous/node_modules/chimera/lib/main.js:29
setInterval(webkit.processEvents, 50);
                  ^
TypeError: Cannot read property 'processEvents' of undefined
    at Object.<anonymous> (/home/ubuntu/talous/node_modules/chimera/lib/main.js:29:19)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/ubuntu/talous/index2.js:1:77)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)

**Comment by Trindaz** [comment]
(and incase you're wondering about the upgrade to node 0.8.17, the reason is that Ubuntu 12's default nodejs 0.6 doesn't have fs.existsSync which is used in /chimera/lib/main.js)

**Comment by deanmao** [comment]
is this a 64bit ubuntu?

**Comment by underbyte** [comment]
This is happening on ubuntu 64bit, seems that the scripts/download_native_binary.js is requesting a file from "http://s3.chimerajs.com/chimera_linux_x64__0.3.2.gz" and the server is returning access denied.

**Comment by christhorwarth** [comment]
I can reproduce this on fresh ubuntu aws instance.

**Comment by fruchtose** [comment]
I'm also seeing this issue in 32-bit Ubuntu 12.04:

```
Using the chimera in lib
Error loading chimera in lib

(snip).../node_modules/chimera/lib/main.js:29
setInterval(webkit.processEvents, 50);
                  ^
TypeError: Cannot read property 'processEvents' of undefined
    at Object.<anonymous> (/home/robert/muxamp/node_modules/chimera/lib/main.js:29:19)
...(snip)
```

**Comment by eugenioclrc** [comment]
same error to me...

Ver ubuntu 12.04 (precise) de 64-bit
Linux 3.2.0-38-generic

**Comment by jedahan** [comment]
same error on OSX 10.8 with node 0.8.22 and 0.10.2

**Comment by ak5** [comment]
I am getting the same thing on linux with node v0.10.7
