### ISSUE TITLE
node v0.10.x

### ISSUE THREAD

**Issue by jney** [deanmao/node-chimera#26]
Hi,

I've got the following error while trying to requiring `chimera.node` using node v0.10.0, and seems to work with v0.8.x

```
$ node        
> require('./chimera')
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

Thx

By the way, is the project still supported ?

**Comment by mikecluck** [comment]
Bump.

I've got a similar problem using node v0.9.3

```
$ node
> require('chimera')
Using the chimera in lib
[Error: Module version mismatch. Expected 10, got 1.]
Error loading chimera in lib
TypeError: Cannot read property 'processEvents' of undefined
    at Object.<anonymous> (node_modules/chimera/lib/main.js:30:19)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:248:12)
```

**Comment by dhendo** [comment]
Hi Guys, can you edit lib/main.js to add the console.log(e) and return if webkit isn't instantiated as in
https://github.com/dhendo/node-chimera/blob/build-on-ubuntu64/lib/main.js

and run examples/example.js and post the output?

I'm currently getting 

```
Using the custom built chimera
[Error: /home/davidh/dev/github/node-chimera/build/Release/chimera.node: undefined symbol: _ZNK9QMimeData10metaObjectEv]
Using the chimera in lib
[Error: /home/davidh/dev/github/node-chimera/lib/chimera.node: undefined symbol: _ZNK9QMimeData10metaObjectEv]
Error loading chimera in lib
Failed to load webkit
```

But this is against a custom-built version of chimera on node 0.10.4
