### ISSUE TITLE
Error wrong ELF class: ELFCLASS64 in Ubuntu 32bit

### ISSUE THREAD

**Issue by olragon** [deanmao/node-chimera#5]
I try Chimera with code below

lib/spider.js

```
var chimera = require('chimera').Chimera;

var Chimera = new chimera();

Chimera.perform({
    url: 'http://google.com',
    run: function(callback) {
        callback(null, 'success');
    },
    callback: function(err, result) {
        console.log('here are the cookies');
        console.log(Chimera.cookies());
    }
});
```

Stack trace

```
module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: /xxx/project/node_modules/chimera/native/linux/v0.8/chimera.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/xxx/project/node_modules/chimera/lib/main.js:6:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

node -v

```
v0.8.8
```

uname -a

```
Linux xxx 3.2.0-35-generic-pae #55-Ubuntu SMP Wed Dec 5 18:04:39 UTC 2012 i686 i686 i386 GNU/Linux
```

cat /etc/lsb-release

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.1 LTS"
```

**Comment by deanmao** [comment]
Yes, I don't have a 32bit compiled chimera yet.  If you're on linux, you'll need 64bit or wait for the precompiled stuff.

**Comment by olragon** [comment]
I wait for precompiled 32bit version. If I can help, let's me know.

**Comment by deanmao** [comment]
I included instructions for compiling on different machines.  let me know if you have issues with compiling.

**Comment by deanmao** [comment]
32bit binary is done, fetch new version to have it installed.  (npm install chimera)
