### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by bitliner** [deanmao/node-chimera#50]
It throws the following error during installation

```

> chimera@0.3.2 postinstall /home/*/projects/logged-in-crawler/node_modules/chimera
> node scripts/download_native_binary.js

downloading chimera native binary for: linux_x64

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! chimera@0.3.2 postinstall: `node scripts/download_native_binary.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chimera@0.3.2 postinstall script.
npm ERR! This is most likely a problem with the chimera package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/download_native_binary.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chimera
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-38-generic
npm ERR! command "/home/*/v0.10.22/bin/node" "/home/*/v0.10.22/bin/npm" "install" "chimera"
npm ERR! cwd /home/*/projects/logged-in-crawler
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/*/projects/logged-in-crawler/npm-debug.log
npm ERR! not ok code 0


```

**Comment by dhendo** [comment]
I believe the domain chimera-js.com has lapsed

**Comment by jeffmarshall** [comment]
@dhendo: Could the binaries be left out of version control but bundled with the NPM package? Can you upload them to mega.co or something for the time being?

**Comment by dhendo** [comment]
@jeffmarshall I don't have the version of the binaries that lived on chimera-js.com - you may have some luck with the version I built in https://github.com/deanmao/node-chimera/issues/34#issuecomment-19394050

**Comment by grssnbchr** [comment]
Got exactly the same error, still. I am on Ubuntu 12.04 64bit.
