### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by frankred** [deanmao/node-chimera#54]
Working on Windows7 64-Bit, getting the following error:

```
C:\workspace-js\nodejs-example>npm install chimera
npm info it worked if it ends with ok
npm info using npm@1.3.8
npm info using node@v0.10.16
npm info trying registry request attempt 1 at 13:29:54
npm http GET https://registry.npmjs.org/chimera
npm http 200 https://registry.npmjs.org/chimera
npm info retry fetch attempt 1 at 13:29:55
npm http GET https://registry.npmjs.org/chimera/-/chimera-0.3.2.tgz
npm http 200 https://registry.npmjs.org/chimera/-/chimera-0.3.2.tgz
npm info install chimera@0.3.2 into C:\workspace-js\nodejs-example
npm info installOne chimera@0.3.2
npm info C:\workspace-js\nodejs-example\node_modules\chimera unbuild
npm info preinstall chimera@0.3.2
npm info trying registry request attempt 1 at 13:29:56
npm http GET https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/request
npm info retry fetch attempt 1 at 13:29:56
npm http GET https://registry.npmjs.org/request/-/request-2.12.0.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.12.0.tgz
npm info install request@2.12.0 into C:\workspace-js\nodejs-example\node_modules\chimera
npm info installOne request@2.12.0
npm info C:\workspace-js\nodejs-example\node_modules\chimera\node_modules\request unbuild
npm info preinstall request@2.12.0
npm info build C:\workspace-js\nodejs-example\node_modules\chimera\node_modules\request
npm info linkStuff request@2.12.0
npm info build C:\workspace-js\nodejs-example\node_modules\chimera\node_modules\request\node_modules\form-data
npm info preinstall form-data@0.0.3
npm info linkStuff form-data@0.0.3
npm info install form-data@0.0.3
npm info postinstall form-data@0.0.3
npm info build C:\workspace-js\nodejs-example\node_modules\chimera\node_modules\request\node_modules\mime
npm info preinstall mime@1.2.7
npm info linkStuff mime@1.2.7
npm info install mime@1.2.7
npm info postinstall mime@1.2.7
npm info install request@2.12.0
npm info postinstall request@2.12.0
npm info build C:\workspace-js\nodejs-example\node_modules\chimera
npm info linkStuff chimera@0.3.2
npm info install chimera@0.3.2
npm info postinstall chimera@0.3.2

> chimera@0.3.2 postinstall C:\workspace-js\nodejs-example\node_modules\chimera
> node scripts/download_native_binary.js

downloading chimera native binary for: win32_x64

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm info chimera@0.3.2 Failed to exec postinstall script
npm info C:\workspace-js\nodejs-example\node_modules\chimera unbuild
npm info preuninstall chimera@0.3.2
npm info uninstall chimera@0.3.2
npm info postuninstall chimera@0.3.2
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by bugs181** [comment]
Same here. Hoping to see this resolved soon. Just came across chimera and it looks exactly like what I want. Phantom isn't cutting it for me.

**Comment by methuz** [comment]
same here on OSX Yosemite

```
chimera/ npm install chimera --save
|
> chimera@0.3.2 postinstall /Users/Methuz/Workspace/Learning/node_modules/chimera
> node scripts/download_native_binary.js

downloading chimera native binary for: darwin_x64

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "chimera" "--save"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! chimera@0.3.2 postinstall: `node scripts/download_native_binary.js`
npm ERR! Exit status 8
```

**Comment by amichaelgrant** [comment]
Does Chimera ever install? Has anyone been able to successfully install it?
I am attempting to install on ubuntu and getting the errors below:
npm install chimera
npm WARN package.json crypto@0.0.3 crypto is also the name of a node core module.
|

> chimera@0.3.2 postinstall /home/grant/Projects/protodev/node_modules/chimera
> node scripts/download_native_binary.js

downloading chimera native binary for: linux_ia32

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:124:16)

npm ERR! chimera@0.3.2 postinstall: `node scripts/download_native_binary.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chimera@0.3.2 postinstall script.
npm ERR! This is most likely a problem with the chimera package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/download_native_binary.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chimera
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "chimera"
npm ERR! cwd /home/grant/Projects/protodev
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by kucukkanat** [comment]
Still not solved the issue. Can't install on Yosemite either. Where is the developer? Come on?!

**Comment by mysurk** [comment]
Same Problem.. Could not go through installation. Is this package not maintained?

npm ERR! Linux 3.17.2-200.fc20.x86_64
npm ERR! argv "node" "/bin/npm" "install" "chimera"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.5
npm ERR! code ELIFECYCLE

npm ERR! chimera@0.3.2 postinstall: `node scripts/download_native_binary.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chimera@0.3.2 postinstall script.
npm ERR! This is most likely a problem with the chimera package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/download_native_binary.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chimera
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by SnakeO** [comment]
same issue

node scripts/download_native_binary.js

downloading chimera native binary for: linux_x64
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND s3.chimerajs.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)
npm ERR! Linux 2.6.32-042stab113.21
npm ERR! argv ".nvm/versions/node/v0.12.10/bin/node" ".nvm/versions/node/v0.12.10/bin/npm" "install" "--save" "chimera"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! chimera@0.3.2 postinstall: `node scripts/download_native_binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chimera@0.3.2 postinstall script 'node scripts/download_native_binary.js'.
npm ERR! This is most likely a problem with the chimera package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/download_native_binary.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chimera
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log

**Comment by hems** [comment]
````
downloading chimera native binary for: darwin_x64
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND s3.chimerajs.com s3.chimerajs.com:80
````

**Comment by mgttt** [comment]
project is stopped, right?

**Comment by bugs181** [comment]
> project is stopped, right?

Looks that way, unfortunately.

**Comment by kucukkanat** [comment]
I suggest using Puppeteer sfrom now on
